-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 05, 2025 at 06:05 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `flixgo_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `movies`
--

CREATE TABLE `movies` (
  `id` int(11) NOT NULL,
  `rank` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `year` int(11) NOT NULL,
  `rating` float NOT NULL,
  `genre` varchar(100) NOT NULL,
  `certificate` varchar(50) DEFAULT NULL,
  `run_time` varchar(10) DEFAULT NULL,
  `tagline` text DEFAULT NULL,
  `budget` bigint(20) DEFAULT NULL,
  `box_office` bigint(20) DEFAULT NULL,
  `casts` text DEFAULT NULL,
  `directors` varchar(255) DEFAULT NULL,
  `writers` varchar(255) DEFAULT NULL,
  `image_path` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `movies`
--

INSERT INTO `movies` (`id`, `rank`, `name`, `year`, `rating`, `genre`, `certificate`, `run_time`, `tagline`, `budget`, `box_office`, `casts`, `directors`, `writers`, `image_path`) VALUES
(1, 1, 'The Shawshank Redemption', 1994, 9.3, 'Drama', 'R', '2h 22m', 'Fear can hold you prisoner. Hope can set you free.', 25000000, 28884504, 'Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,Clancy Brown,Gil Bellows,Mark Rolston,James Whitmore,Jeffrey DeMunn,Larry Brandenburg,Neil Giuntoli,Brian Libby,David Proval,Joseph Ragno,Jude Ciccolella,Paul McCrane,Renee Blaine,Scott Mann', 'Frank Darabont', 'Stephen King,Frank Darabont', 'movie_image_01.jpg'),
(2, 2, 'The Godfather', 1972, 9.2, 'Crime,Drama', 'R', '2h 55m', 'An offer you can\'t refuse.', 6000000, 250341816, 'Marlon Brando,Al Pacino,James Caan,Diane Keaton,Richard S. Castellano,Robert Duvall,Sterling Hayden,John Marley,Richard Conte,Al Lettieri,Abe Vigoda,Talia Shire,Gianni Russo,John Cazale,Rudy Bond,Al Martino,Morgana King,Lenny Montana', 'Francis Ford Coppola', 'Mario Puzo,Francis Ford Coppola', 'movie_image_02.jpg'),
(3, 3, 'The Dark Knight', 2008, 9, 'Action,Crime,Drama', 'PG-13', '2h 32m', 'Why So Serious?', 185000000, 1006234167, 'Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,Maggie Gyllenhaal,Gary Oldman,Morgan Freeman,Monique Gabriela Curnen,Ron Dean,Cillian Murphy,Chin Han,Nestor Carbonell,Eric Roberts,Ritchie Coster,Anthony Michael Hall,Keith Szarabajka,Colin McFarlane,Joshua Harto', 'Christopher Nolan', 'Jonathan Nolan,Christopher Nolan,David S. Goyer', 'movie_image_03.jpg'),
(4, 4, 'The Godfather Part II', 1974, 9, 'Crime,Drama', 'R', '3h 22m', 'All the power on earth can\'t change destiny.', 13000000, 47961919, 'Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,John Cazale,Talia Shire,Lee Strasberg,Michael V. Gazzo,G.D. Spradlin,Richard Bright,Gastone Moschin,Tom Rosqui,Bruno Kirby,Frank Sivero,Francesca De Sapio,Morgana King,Marianna Hill,Leopoldo Trieste', 'Francis Ford Coppola', 'Francis Ford Coppola,Mario Puzo', 'movie_image_04.jpg'),
(5, 5, '12 Angry Men', 1957, 9, 'Crime,Drama', 'Approved', '1h 36m', 'Life Is In Their Hands -- Death Is On Their Minds!', 350000, 955, 'Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,E.G. Marshall,Jack Klugman,Edward Binns,Jack Warden,Joseph Sweeney,Ed Begley,George Voskovec,Robert Webber,Rudy Bond,Tom Gorman,James Kelly,Billy Nelson,John Savoca,Walter Stocker', 'Sidney Lumet', 'Reginald Rose', 'movie_image_05.jpg'),
(6, 6, 'Schindler\'s List', 1993, 9, 'Biography,Drama,History', 'R', '3h 15m', 'Whoever saves one life, saves the world entire.', 22000000, 322161245, 'Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,Jonathan Sagall,Embeth Davidtz,Malgorzata Gebel,Shmuel Levy,Mark Ivanir,Béatrice Macola,Andrzej Seweryn,Friedrich von Thun,Krzysztof Luft,Harry Nehring,Norbert Weisser,Adi Nitzan,Michael Schneider,Miri Fabian', 'Steven Spielberg', 'Thomas Keneally,Steven Zaillian', 'movie_image_06.jpg'),
(7, 7, 'The Lord of the Rings: The Return of the King', 2003, 9, 'Action,Adventure,Drama', 'PG-13', '3h 21m', 'The eye of the enemy is moving.', 94000000, 1146457748, 'Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,Noel Appleby,Ali Astin,Sean Astin,David Aston,John Bach,Sean Bean,Cate Blanchett,Billy Boyd,Sadwyn Brophy,Alistair Browning,Marton Csokas,Richard Edge,Jason Fitch,Bernard Hill', 'Peter Jackson', 'J.R.R. Tolkien,Fran Walsh,Philippa Boyens', 'movie_image_07.jpg'),
(8, 8, 'Pulp Fiction', 1994, 8.9, 'Crime,Drama', 'R', '2h 34m', 'Girls like me don\'t make invitations like this to just anyone!', 8000000, 213928762, 'John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,Tim Roth,Amanda Plummer,Laura Lovelace,Phil LaMarr,Frank Whaley,Burr Steers,Ving Rhames,Paul Calderon,Bronagh Gallagher,Rosanna Arquette,Eric Stoltz,Jerome Patrick Hoban,Michael Gilden,Gary Shorelle', 'Quentin Tarantino', 'Quentin Tarantino,Roger Avary', 'movie_image_08.jpg'),
(9, 9, 'The Lord of the Rings: The Fellowship of the Ring', 2001, 8.8, 'Action,Adventure,Drama', 'PG-13', '2h 58m', 'The Legend Comes to Life', 93000000, 898204420, 'Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,Alan Howard,Noel Appleby,Sean Astin,Sala Baker,Billy Boyd,Andy Serkis,Marton Csokas,Viggo Mortensen,Megan Edwards,Michael Elsworth,Cate Blanchett,Mark Ferguson,Ian Holm,Christopher Lee', 'Peter Jackson', 'J.R.R. Tolkien,Fran Walsh,Philippa Boyens', 'movie_image_09.jpg'),
(10, 10, 'The Good, the Bad and the Ugly', 1966, 8.8, 'Adventure,Western', 'Approved', '2h 58m', 'They formed an alliance of hate to steal a fortune in dead man\'s gold', 1200000, 25253887, 'Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo Giuffrè,Luigi Pistilli,Rada Rassimov,Enzo Petito,Claudio Scarchilli,John Bartha,Livio Lorenzon,Antonio Casale,Sandro Scarchilli,Benito Stefanelli,Angelo Novi,Antonio Casas,Aldo Sambrell,Al Mulock,Sergio Mendizábal', 'Sergio Leone', 'Luciano Vincenzoni,Sergio Leone,Agenore Incrocci', 'movie_image_10.jpg'),
(11, 11, 'Forrest Gump', 1994, 8.8, 'Drama,Romance', 'PG-13', '2h 22m', 'The story of a lifetime.', 55000000, 678226465, 'Tom Hanks,Robin Wright,Gary Sinise,Sally Field,Rebecca Williams,Michael Conner Humphreys,Harold G. Herthum,George Kelly,Bob Penny,John Randall,Sam Anderson,Margo Moorer,Ione M. Telech,Christine Seabrook,John Worsham,Peter Dobson,Siobhan Fallon Hogan,Alexander Zemeckis', 'Robert Zemeckis', 'Winston Groom,Eric Roth', 'movie_image_11.jpg'),
(12, 12, 'Fight Club', 1999, 8.8, 'Drama', 'R', '2h 19m', 'How much can you know about yourself if you\'ve never been in a fight?', 63000000, 101209702, 'Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,Richmond Arquette,David Andrews,George Maguire,Eugenie Bondurant,Christina Cabot,Helena Bonham Carter,Sydney \'Big Dawg\' Colston,Rachel Singer,Christie Cronenweth,Tim DeZarn,Ezra Buzzington,Dierdre Downing-Jackson,Bob Stephenson,Charlie Dell', 'David Fincher', 'Chuck Palahniuk,Jim Uhls', 'movie_image_12.jpg'),
(13, 13, 'The Lord of the Rings: The Two Towers', 2002, 8.8, 'Action,Adventure,Drama', 'PG-13', '2h 59m', 'A New Power Is Rising.', 94000000, 947944270, 'Elijah Wood,Ian McKellen,Viggo Mortensen,Orlando Bloom,Bruce Allpress,Sean Astin,John Bach,Sala Baker,Cate Blanchett,Billy Boyd,Jed Brophy,Sam Comery,Brad Dourif,Calum Gittins,Bernard Hill,Bruce Hopkins,Paris Howe Strewe,Christopher Lee', 'Peter Jackson', 'J.R.R. Tolkien,Fran Walsh,Philippa Boyens', 'movie_image_13.jpg'),
(14, 14, 'Inception', 2010, 8.8, 'Action,Adventure,Sci-Fi', 'PG-13', '2h 28m', 'Your mind is the scene of the crime', 160000000, 836848102, 'Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,Tom Hardy,Dileep Rao,Cillian Murphy,Tom Berenger,Marion Cotillard,Pete Postlethwaite,Michael Caine,Lukas Haas,Tai-Li Lee,Claire Geare,Magnus Nolan,Taylor Geare,Johnathan Geare,Tohoru Masamune', 'Christopher Nolan', 'Christopher Nolan', 'movie_image_14.jpg'),
(15, 15, 'Star Wars: Episode V - The Empire Strikes Back', 1980, 8.7, 'Action,Adventure,Fantasy', 'PG', '2h 4m', 'The Adventure Continues...', 18000000, 538375067, 'Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,Anthony Daniels,David Prowse,Peter Mayhew,Kenny Baker,Frank Oz,Alec Guinness,Jeremy Bulloch,John Hollis,Jack Purvis,Des Webb,Clive Revill,Kenneth Colley,Julian Glover,Michael Sheard', 'Irvin Kershner', 'Leigh Brackett,Lawrence Kasdan,George Lucas', 'movie_image_15.jpg'),
(16, 16, 'The Matrix', 1999, 8.7, 'Action,Sci-Fi', 'R', '2h 16m', 'Free your mind', 63000000, 467222728, 'Keanu Reeves,Laurence Fishburne,Carrie-Anne Moss,Hugo Weaving,Gloria Foster,Joe Pantoliano,Marcus Chong,Julian Arahanga,Matt Doran,Belinda McClory,Anthony Ray Parker,Paul Goddard,Robert Taylor,David Aston,Marc Aden Gray,Ada Nicodemou,Deni Gordon,Rowan Witt', 'Lana Wachowski,Lilly Wachowski', 'Lilly Wachowski,Lana Wachowski', 'movie_image_16.jpg'),
(17, 17, 'Goodfellas', 1990, 8.7, 'Biography,Crime,Drama', 'R', '2h 25m', '\"As far back as I can remember, I\'ve always wanted to be a gangster.\" -- Henry Hill, Brooklyn, N.Y. 1955.', 25000000, 47036784, 'Robert De Niro,Ray Liotta,Joe Pesci,Lorraine Bracco,Paul Sorvino,Frank Sivero,Tony Darrow,Mike Starr,Frank Vincent,Chuck Low,Frank DiLeo,Henny Youngman,Gina Mastrogiacomo,Catherine Scorsese,Charles Scorsese,Suzanne Shepherd,Debi Mazar,Margo Winkler', 'Martin Scorsese', 'Nicholas Pileggi,Martin Scorsese', 'movie_image_17.jpg'),
(18, 18, 'One Flew Over the Cuckoo\'s Nest', 1975, 8.7, 'Drama', '18+', '2h 13m', 'If he\'s crazy, what does that make you?', 3000000, 109114817, 'Jack Nicholson,Louise Fletcher,Michael Berryman,Peter Brocco,Dean R. Brooks,Alonzo Brown,Scatman Crothers,Mwako Cumbuka,Danny DeVito,William Duell,Josip Elic,Lan Fendors,Nathan George,Ken Kenny,Mel Lambert,Sydney Lassick,Kay Lee,Christopher Lloyd', 'Milos Forman', 'Lawrence Hauben,Bo Goldman,Ken Kesey', 'movie_image_18.jpg'),
(19, 19, 'Se7en', 1995, 8.6, 'Crime,Drama,Mystery', 'R', '2h 7m', 'Long is the way, and hard, that out of hell leads up to light.', 33000000, 327333559, 'Morgan Freeman,Brad Pitt,Kevin Spacey,Andrew Kevin Walker,Daniel Zacapa,Gwyneth Paltrow,John Cassini,Bob Mack,Peter Crombie,Reg E. Cathey,R. Lee Ermey,George Christy,Endre Hules,Hawthorne James,William Davidson,Bob Collins,Jimmy Dale Hartsell,Richard Roundtree', 'David Fincher', 'Andrew Kevin Walker', 'movie_image_19.jpg'),
(20, 20, 'Seven Samurai', 1954, 8.6, 'Action,Drama', 'Not Rated', '3h 27m', 'Will Take Its Place With the Seven Greatest Films of All Time!', 125000000, 346258, 'Toshirô Mifune,Takashi Shimura,Keiko Tsushima,Yukiko Shimazaki,Kamatari Fujiwara,Daisuke Katô,Isao Kimura,Minoru Chiaki,Seiji Miyaguchi,Yoshio Kosugi,Bokuzen Hidari,Yoshio Inaba,Yoshio Tsuchiya,Kokuten Kôdô,Eijirô Tôno,Kichijirô Ueda,Jun Tatara,Atsushi Watanabe', 'Akira Kurosawa', 'Akira Kurosawa,Shinobu Hashimoto,Hideo Oguni', 'movie_image_20.jpg'),
(21, 21, 'It\'s a Wonderful Life', 1946, 8.6, 'Drama,Family,Fantasy', 'PG', '2h 10m', 'Frank Capra\'s...It\'s a Wonderful Life.', 3180000, 8574081, 'James Stewart,Donna Reed,Lionel Barrymore,Thomas Mitchell,Henry Travers,Beulah Bondi,Frank Faylen,Ward Bond,Gloria Grahame,H.B. Warner,Frank Albertson,Todd Karns,Samuel S. Hinds,Mary Treen,Virginia Patton,Charles Williams,Sarah Edwards,William Edmunds', 'Frank Capra', 'Frances Goodrich,Albert Hackett,Frank Capra', 'movie_image_21.jpg'),
(22, 22, 'The Silence of the Lambs', 1991, 8.6, 'Crime,Drama,Thriller', 'R', '1h 58m', 'Dr. Hannibal Lecter. Brilliant. Cunning. Psychotic. In his mind lies the clue to a ruthless killer. - Clarice Starling, FBI. Brilliant. Vulnerable. Alone. She must trust him to stop the killer.', 19000000, 272742922, 'Jodie Foster,Anthony Hopkins,Lawrence A. Bonney,Kasi Lemmons,Lawrence T. Wrentz,Scott Glenn,Anthony Heald,Frankie Faison,Don Brockett,Frank Seals Jr.,Stuart Rudin,Maria Skorobogatov,Jeffrie Lane,Leib Lensky,George \'Red\' Schwartz,Jim Roche,Brooke Smith,Ted Levine', 'Jonathan Demme', 'Thomas Harris,Ted Tally', 'movie_image_22.jpg'),
(23, 23, 'City of God', 2002, 8.6, 'Crime,Drama', 'R', '2h 10m', 'If you run, the beast will get you. If you stay, the beast will eat you', 3300000, 30680793, 'Alexandre Rodrigues,Leandro Firmino,Matheus Nachtergaele,Phellipe Haagensen,Douglas Silva,Jonathan Haagensen,Seu Jorge,Jefechander Suplino,Alice Braga,Emerson Gomes,Edson Oliveira,Michel Gomes,Roberta Rodrigues,Luis Otávio,Kiko Marques,Gustavo Engrácia,Darlan Cunha,Robson Rocha', 'Fernando Meirelles,Kátia Lund(co-director)', 'Paulo Lins,Bráulio Mantovani', 'movie_image_23.jpg'),
(24, 24, 'Saving Private Ryan', 1998, 8.6, 'Drama,War', 'R', '2h 49m', 'In the Last Great Invasion of the Last Great War, The Greatest Danger for Eight Men was Saving... One.', 70000000, 482349603, 'Tom Hanks,Matt Damon,Tom Sizemore,Edward Burns,Barry Pepper,Adam Goldberg,Vin Diesel,Giovanni Ribisi,Jeremy Davies,Ted Danson,Paul Giamatti,Dennis Farina,Joerg Stadler,Max Martini,Dylan Bruno,Daniel Cerqueira,Demetri Goritsas,Ian Porter', 'Steven Spielberg', 'Robert Rodat', 'movie_image_24.jpg'),
(25, 25, 'Interstellar', 2014, 8.6, 'Adventure,Drama,Sci-Fi', 'PG-13', '2h 49m', 'Mankind was born on Earth. It was never meant to die here.', 165000000, 773867216, 'Matthew McConaughey,Anne Hathaway,Jessica Chastain,Mackenzie Foy,Ellen Burstyn,John Lithgow,Timothée Chalamet,David Oyelowo,Collette Wolfe,Francis X. McCarthy,Bill Irwin,Andrew Borba,Wes Bentley,William Devane,Michael Caine,David Gyasi,Josh Stewart,Casey Affleck', 'Christopher Nolan', 'Jonathan Nolan,Christopher Nolan', 'movie_image_25.jpg'),
(26, 26, 'Life Is Beautiful', 1997, 8.6, 'Comedy,Drama,Romance', 'PG-13', '1h 56m', 'An unforgettable fable that proves love, family and imagination conquer all. (Canadian one sheet)', 20000000, 230098753, 'Roberto Benigni,Nicoletta Braschi,Giorgio Cantarini,Giustino Durano,Sergio Bini Bustric,Marisa Paredes,Horst Buchholz,Lidia Alfonsi,Giuliana Lojodice,Amerigo Fontani,Pietro De Silva,Francesco Guzzo,Raffaella Lebboroni,Claudio Alfonsi,Gil Baroni,Massimo Bianchi,Jürgen Bohn,Verena Buratti', 'Roberto Benigni', 'Vincenzo Cerami,Roberto Benigni', 'movie_image_26.jpg'),
(27, 27, 'The Green Mile', 1999, 8.6, 'Crime,Drama,Fantasy', 'R', '3h 9m', 'Miracles do happen.', 60000000, 286801374, 'Tom Hanks,Michael Clarke Duncan,David Morse,Bonnie Hunt,James Cromwell,Michael Jeter,Graham Greene,Doug Hutchison,Sam Rockwell,Barry Pepper,Jeffrey DeMunn,Patricia Clarkson,Harry Dean Stanton,Dabbs Greer,Eve Brent,William Sadler,Mack Miles,Rai Tasco', 'Frank Darabont', 'Stephen King,Frank Darabont', 'movie_image_27.jpg'),
(28, 28, 'Star Wars: Episode IV - A New Hope', 1977, 8.6, 'Action,Adventure,Fantasy', 'PG', '2h 1m', 'It\'s Back! The Force will be with you for three weeks only. (1979 Reissue Poster)', 11000000, 775398007, 'Mark Hamill,Harrison Ford,Carrie Fisher,Alec Guinness,Peter Cushing,Anthony Daniels,Kenny Baker,Peter Mayhew,David Prowse,Phil Brown,Shelagh Fraser,Jack Purvis,Alex McCrindle,Eddie Byrne,Drewe Henley,Denis Lawson,Garrick Hagon,Jack Klaff', 'George Lucas', 'George Lucas', 'movie_image_28.jpg'),
(29, 29, 'Terminator 2: Judgment Day', 1991, 8.6, 'Action,Sci-Fi', 'R', '2h 17m', 'It\'s nothing personal.', 102000000, 520881154, 'Arnold Schwarzenegger,Linda Hamilton,Edward Furlong,Robert Patrick,Earl Boen,Joe Morton,S. Epatha Merkerson,Castulo Guerra,Danny Cooksey,Jenette Goldstein,Xander Berkeley,Leslie Hamilton Gearren,Ken Gibbel,Robert Winley,Peter Schrum,Shane Wilder,Michael Edwards,Jared Lounsbery', 'James Cameron', 'James Cameron,William Wisher', 'movie_image_29.jpg'),
(30, 30, 'Back to the Future', 1985, 8.5, 'Adventure,Comedy,Sci-Fi', 'PG', '1h 56m', 'He\'s the only kid ever to get into trouble before he was born. [UK]', 19000000, 383336762, 'Michael J. Fox,Christopher Lloyd,Lea Thompson,Crispin Glover,Tom Wilson,Claudia Wells,Marc McClure,Wendie Jo Sperber,George DiCenzo,Frances Lee McCain,James Tolkan,J.J. Cohen,Casey Siemaszko,Billy Zane,Harry Waters Jr.,Donald Fullilove,Lisa Freeman,Cristen Kauffman', 'Robert Zemeckis', 'Robert Zemeckis,Bob Gale', 'movie_image_30.jpg'),
(31, 31, 'Spirited Away', 2001, 8.6, 'Animation,Adventure,Family', 'PG', '2h 5m', 'The tunnel led Chihiro to a mysterious town.', 19000000, 355822319, 'Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,Mari Natsuki,Takashi Naitô,Yasuko Sawaguchi,Tatsuya Gashûin,Ryûnosuke Kamiki,Yumi Tamai,Yô Ôizumi,Koba Hayashi,Tsunehiko Kamijô,Takehiko Ono,Bunta Sugawara,Shigeru Wakita,Shirô Saitô,Michiko Yamamoto', 'Hayao Miyazaki', 'Hayao Miyazaki', 'movie_image_31.jpg'),
(32, 32, 'The Pianist', 2002, 8.5, 'Biography,Drama,Music', 'R', '2h 30m', 'Music was his passion. Survival was his masterpiece.', 35000000, 120072577, 'Adrien Brody,Thomas Kretschmann,Frank Finlay,Emilia Fox,Michal Zebrowski,Ed Stoppard,Maureen Lipman,Jessica Kate Meyer,Julia Rayner,Wanja Mues,Richard Ridings,Nomi Sharron,Anthony Milner,Lucy Skeaping,Roddy Skeaping,Ben Harlan,Thomas Lawinky,Joachim Paul Assböck', 'Roman Polanski', 'Ronald Harwood,Wladyslaw Szpilman', 'movie_image_32.jpg'),
(33, 33, 'Psycho', 1960, 8.5, 'Horror,Mystery,Thriller', 'R', '1h 49m', 'The picture you MUST see from the beginning... Or not at all!... For no one will be seated after the start of... Alfred Hitchcock\'s greatest shocker Psycho.', 806947, 32052925, 'Anthony Perkins,Janet Leigh,Vera Miles,John Gavin,Martin Balsam,John McIntire,Simon Oakland,Frank Albertson,Patricia Hitchcock,Vaughn Taylor,Lurene Tuttle,John Anderson,Mort Mills,Fletcher Allen,Walter Bacon,Prudence Beers,Kit Carson,Francis De Sales', 'Alfred Hitchcock', 'Joseph Stefano,Robert Bloch', 'movie_image_33.jpg'),
(34, 34, 'Parasite', 2019, 8.5, 'Drama,Thriller', 'R', '2h 12m', 'Misplaced familyhood (Australia/New Zealand/Singapore)', 11400000, 262676096, 'Song Kang-ho,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,Park So-dam,Lee Jeong-eun,Jang Hye-jin,Park Myeong-hoon,Jung Ji-so,Jung Hyun-jun,Park Keun-rok,Jung Yi-seo,Jo Jae-myeong,Jung Ik-han,Kim Kyu-baek,Hwang In-kyung,Ahn Seong-bong,Kim Jin-hyung', 'Bong Joon Ho', 'Bong Joon Ho,Han Jin-won', 'movie_image_34.jpg'),
(35, 35, 'Léon: The Professional', 1994, 8.5, 'Action,Crime,Drama', 'R', '1h 50m', 'If you want the job done right, hire a professional.', 115000000, 19569225, 'Jean Reno,Gary Oldman,Natalie Portman,Danny Aiello,Peter Appel,Willi One Blood,Don Creech,Keith A. Glascoe,Randolph Scott,Michael Badalucco,Ellen Greene,Elizabeth Regen,Carl J. Matusovich,Frank Senger,Lucius Wyatt Cherokee,Eric Challier,Luc Bernard,Maïwenn', 'Luc Besson', 'Luc Besson', 'movie_image_35.jpg'),
(36, 36, 'The Lion King', 1994, 8.5, 'Animation,Adventure,Drama', 'G', '1h 28m', 'See it for the first time ever in 3D (2011 3D re-release)', 45000000, 968511805, 'Matthew Broderick,Jeremy Irons,James Earl Jones,Whoopi Goldberg,Rowan Atkinson,Niketa Calame-Harris,Jim Cummings,Robert Guillaume,Moira Kelly,Nathan Lane,Zoe Leader,Cheech Marin,Ernie Sabella,Madge Sinclair,Jonathan Taylor Thomas,Frank Welker,Cathy Cavadini,Judi M. Durand', 'Roger Allers,Rob Minkoff', 'Irene Mecchi,Jonathan Roberts,Linda Woolverton', 'movie_image_36.jpg'),
(37, 37, 'Gladiator', 2000, 8.5, 'Action,Adventure,Drama', 'R', '2h 35m', 'Father of a murdered son, husband to a murdered wife and I shall have my vengeance in this life or the next', 103000000, 503162313, 'Russell Crowe,Joaquin Phoenix,Connie Nielsen,Oliver Reed,Richard Harris,Derek Jacobi,Djimon Hounsou,David Schofield,John Shrapnel,Tomas Arana,Ralf Moeller,Spencer Treat Clark,David Hemmings,Tommy Flanagan,Sven-Ole Thorsen,Omid Djalili,Nicholas McGaughey,Chris Kell', 'Ridley Scott', 'David Franzoni,John Logan,William Nicholson', 'movie_image_37.jpg'),
(38, 38, 'American History X', 1998, 8.5, 'Crime,Drama', 'R', '1h 59m', 'His father taught him to hate. His friends taught him rage. His enemies gave him hope.', 20000000, 23875127, 'Edward Norton,Edward Furlong,Beverly D\'Angelo,Jennifer Lien,Ethan Suplee,Fairuza Balk,Avery Brooks,Elliott Gould,Stacy Keach,William Russ,Guy Torry,Joe Cortese,Jason Bose Smith,Antonio David Lyons,Alex Sol,Keram Malicki-Sánchez,Giuseppe Andrews,Michelle Christine White', 'Tony Kaye', 'David McKenna', 'movie_image_38.jpg'),
(39, 39, 'The Departed', 2006, 8.5, 'Crime,Drama,Thriller', 'R', '2h 31m', 'Lies. Betrayal. Sacrifice. How far will you take it?', 90000000, 291480452, 'Leonardo DiCaprio,Matt Damon,Jack Nicholson,Mark Wahlberg,Martin Sheen,Ray Winstone,Vera Farmiga,Anthony Anderson,Alec Baldwin,Kevin Corrigan,James Badge Dale,David O\'Hara,Mark Rolston,Robert Wahlberg,Kristen Dalton,Thomas B. Duffy,Richard Hughes,J.C. MacKenzie', 'Martin Scorsese', 'William Monahan,Alan Mak,Felix Chong', 'movie_image_39.jpg'),
(40, 40, 'The Usual Suspects', 1995, 8.5, 'Crime,Drama,Mystery', 'R', '1h 46m', 'The greatest trick the devil ever pulled was to convince the world he didn\'t exist', 6000000, 23341568, 'Kevin Spacey,Gabriel Byrne,Chazz Palminteri,Stephen Baldwin,Benicio Del Toro,Kevin Pollak,Pete Postlethwaite,Suzy Amis,Giancarlo Esposito,Dan Hedaya,Paul Bartel,Carl Bressler,Phillipe Simon,Jack Shearer,Christine Estabrook,Clark Gregg,Morgan Hunter,Ken Daly', 'Bryan Singer', 'Christopher McQuarrie', 'movie_image_40.jpg'),
(41, 41, 'The Prestige', 2006, 8.5, 'Drama,Mystery,Sci-Fi', 'PG-13', '2h 10m', 'A Friendship That Became a Rivalry.', 40000000, 109676311, 'Christian Bale,Hugh Jackman,Scarlett Johansson,Michael Caine,Piper Perabo,Rebecca Hall,Samantha Mahurin,David Bowie,Andy Serkis,Daniel Davis,Jim Piddock,Christopher Neame,Mark Ryan,Roger Rees,Jamie Harris,Monty Stuart,Ron Perkins,Ricky Jay', 'Christopher Nolan', 'Jonathan Nolan,Christopher Nolan,Christopher Priest', 'movie_image_41.jpg'),
(42, 42, 'Whiplash', 2014, 8.5, 'Drama,Music', 'R', '1h 46m', 'The road to greatness can take you to the edge', 3300000, 49396747, 'Miles Teller,J.K. Simmons,Melissa Benoist,Paul Reiser,Austin Stowell,Nate Lang,Chris Mulkey,Damon Gupton,Suanne Spoke,Max Kasch,Charlie Ian,Jayson Blair,Kofi Siriboe,Kavita Patil,C.J. Vana,Tarik Lowe,Tyler Kimball,Rogelio Douglas Jr.', 'Damien Chazelle', 'Damien Chazelle', 'movie_image_42.jpg'),
(43, 43, 'Casablanca', 1942, 8.5, 'Drama,Romance,War', 'PG', '1h 42m', 'Where Love Cuts as Deep as a Dagger!', 950000, 4626532, 'Humphrey Bogart,Ingrid Bergman,Paul Henreid,Claude Rains,Conrad Veidt,Sydney Greenstreet,Peter Lorre,S.Z. Sakall,Madeleine Lebeau,Dooley Wilson,Joy Page,John Qualen,Leonid Kinskey,Curt Bois,Abdullah Abbas,Enrique Acosta,Ed Agresti,Arnet Amos', 'Michael Curtiz', 'Julius J. Epstein,Philip G. Epstein,Howard Koch', 'movie_image_43.jpg'),
(44, 44, 'Grave of the Fireflies', 1988, 8.5, 'Animation,Drama,War', 'Not Rated', '1h 29m', 'imationDramaWar', 3700000, 516962, 'Tsutomu Tatsumi,Ayano Shiraishi,Akemi Yamaguchi,Yoshiko Shinohara,Kôzô Hashida,Masayo Sakai,Kazumi Nozaki,Yoshio Matsuoka,Masahiro Kanetake,Kiyoshi Yanagawa,Hajime Maki,Atsuo Omote,Teruhisa Harita,Hiroshi Tanaka,Michio Denpô,Shirô Tamaki,Tadashi Nakamura,Mika Sekita', 'Isao Takahata', 'Akiyuki Nosaka,Isao Takahata', 'movie_image_44.jpg'),
(45, 45, 'Harakiri', 1962, 8.6, 'Action,Drama,Mystery', 'Not Rated', '2h 13m', 'The World Has Never Understood Why the Japanese Prefer Death to Dishonor! This Samurai Picture Provides The Answer!!', NULL, NULL, 'Tatsuya Nakadai,Akira Ishihama,Shima Iwashita,Tetsurô Tanba,Masao Mishima,Ichirô Nakatani,Kei Satô,Yoshio Inaba,Hisashi Igawa,Tôru Takeuchi,Yoshirô Aoki,Tatsuo Matsumura,Akiji Kobayashi,Kôichi Hayashi,Ryûtarô Gomi,Jô Azumi,Nakajirô Tomita,Shichisaburô Amatsu', 'Masaki Kobayashi', 'Yasuhiko Takiguchi,Shinobu Hashimoto', 'movie_image_45.jpg'),
(46, 46, 'The Intouchables', 2011, 8.5, 'Biography,Comedy,Drama', 'R', '1h 52m', 'Sometimes you have to reach into someone else\'s world to find out what\'s missing in your own.', 9500000, 426588510, 'François Cluzet,Omar Sy,Anne Le Ny,Audrey Fleurot,Joséphine de Meaux,Clotilde Mollet,Alba Gaïa Bellugi,Cyril Mendy,Salimata Kamate,Absa Diatou Toure,Grégoire Oestermann,Dominique Daguier,François Caron,Christian Ameri,Thomas Solivérès,Dorothée Brière,Marie-Laure Descoureaux,Émilie Caen', 'Olivier Nakache,Éric Toledano', 'Olivier Nakache,Éric Toledano,Philippe Pozzo di Borgo', 'movie_image_46.jpg'),
(47, 47, 'Modern Times', 1936, 8.5, 'Comedy,Drama,Romance', 'G', '1h 27m', 'He stands alone as the greatest entertainer of modern times! No one on earth can make you laugh as heartily or touch your heart as deeply...the whole world laughs, cries and thrills to his priceless genius!', 1500000, 463618, 'Charles Chaplin,Paulette Goddard,Henry Bergman,Tiny Sandford,Chester Conklin,Hank Mann,Stanley Blystone,Al Ernest Garcia,Richard Alexander,Cecil Reynolds,Mira McKinney,Murdock MacQuarrie,Wilfred Lucas,Edward LeSaint,Fred Malatesta,Sammy Stein,Juana Sutton,Ted Oliver', 'Charles Chaplin', 'Charles Chaplin', 'movie_image_47.jpg'),
(48, 48, 'Once Upon a Time in the West', 1968, 8.5, 'Western', 'PG-13', '2h 45m', 'There were three men in her life. One knew her past. One wanted her land. One wanted revenge.', 5000000, 5435024, 'Henry Fonda,Charles Bronson,Claudia Cardinale,Jason Robards,Gabriele Ferzetti,Paolo Stoppa,Woody Strode,Jack Elam,Keenan Wynn,Frank Wolff,Lionel Stander,Livio Andronico,Salvatore Basile,Aldo Berti,Joseph Bradley,Frank Braña,Marilù Carteny,Saturno Cerra', 'Sergio Leone', 'Sergio Donati,Sergio Leone,Dario Argento', 'movie_image_48.jpg'),
(49, 49, 'Rear Window', 1954, 8.5, 'Mystery,Thriller', 'PG', '1h 52m', 'The Essential Hitchcock', 1000000, 37034579, 'James Stewart,Grace Kelly,Wendell Corey,Thelma Ritter,Raymond Burr,Judith Evelyn,Ross Bagdasarian,Georgine Darcy,Sara Berner,Frank Cady,Jesslyn Fax,Rand Harper,Irene Winston,Havis Davenport,Jerry Antes,Barbara Bailey,Benny Bartlett,Nick Borgani', 'Alfred Hitchcock', 'John Michael Hayes,Cornell Woolrich', 'movie_image_49.jpg'),
(50, 50, 'Cinema Paradiso', 1988, 8.5, 'Drama,Romance', 'PG', '2h 35m', 'A celebration of youth, friendship, and the everlasting magic of the movies.', 5000000, 13019063, 'Philippe Noiret,Enzo Cannavale,Antonella Attili,Isa Danieli,Leo Gullotta,Marco Leonardi,Pupella Maggio,Agnese Nano,Leopoldo Trieste,Salvatore Cascio,Tano Cimarosa,Nicola Di Pinto,Roberta Lena,Nino Terzo,Jacques Perrin,Nellina Laganà,Turi Giuffrida,Mariella Lo Giudice', 'Giuseppe Tornatore', 'Giuseppe Tornatore,Vanna Paoli', 'movie_image_50.jpg'),
(51, 51, 'Alien', 1979, 8.5, 'Horror,Sci-Fi', 'R', '1h 57m', 'In space no one can hear you scream.', 11000000, 106285522, 'Sigourney Weaver,Tom Skerritt,John Hurt,Veronica Cartwright,Harry Dean Stanton,Ian Holm,Yaphet Kotto,Bolaji Badejo,Helen Horton,Eddie Powell', 'Ridley Scott', 'Dan O\'Bannon,Ronald Shusett', 'movie_image_51.jpg'),
(52, 52, 'City Lights', 1931, 8.5, 'Comedy,Drama,Romance', 'G', '1h 27m', 'HE RETURNS -And the world rocks again with laughter. (Print Ad-Daily Examiner, ((Grafton, NSW)) 6 July 1931)', 1500000, 50419, 'Charles Chaplin,Virginia Cherrill,Florence Lee,Harry Myers,Al Ernest Garcia,Hank Mann,Johnny Aber,Jack Alexander,T.S. Alexander,Victor Alexander,Albert Austin,Harry Ayers,Eddie Baker,Henry Bergman,Edward Biby,Betty Blair,Buster Brodie,Jeanne Carpenter', 'Charles Chaplin', 'Charles Chaplin,Harry Carr,Harry Crocker', 'movie_image_52.jpg'),
(53, 53, 'Apocalypse Now', 1979, 8.5, 'Drama,Mystery,War', 'R', '2h 27m', 'The Horror. . . The Horror. . .', 31500000, 104880868, 'Martin Sheen,Marlon Brando,Robert Duvall,Frederic Forrest,Sam Bottoms,Laurence Fishburne,Albert Hall,Harrison Ford,Dennis Hopper,G.D. Spradlin,Jerry Ziesmer,Scott Glenn,Bo Byers,James Keane,Kerry Rossall,Ron McQueen,Tom Mason,Cynthia Wood', 'Francis Ford Coppola', 'John Milius,Francis Ford Coppola,Michael Herr', 'movie_image_53.jpg'),
(54, 54, 'Memento', 2000, 8.4, 'Mystery,Thriller', 'R', '1h 53m', 'Some memories are best forgotten', 9000000, 40047078, 'Guy Pearce,Carrie-Anne Moss,Joe Pantoliano,Mark Boone Junior,Russ Fega,Jorja Fox,Stephen Tobolowsky,Harriet Sansom Harris,Thomas Lennon,Callum Keith Rennie,Kimberly Campbell,Marianne Muellerleile,Larry Holden,Stephanie Searson,Buzz Visconti', 'Christopher Nolan', 'Christopher Nolan,Jonathan Nolan', 'movie_image_54.jpg'),
(55, 55, 'Django Unchained', 2012, 8.4, 'Drama,Western', 'R', '2h 45m', 'Life, liberty and the pursuit of vengeance.', 100000000, 426074373, 'Jamie Foxx,Christoph Waltz,Leonardo DiCaprio,Kerry Washington,Samuel L. Jackson,Walton Goggins,Dennis Christopher,James Remar,David Steen,Dana Gourrier,Nichole Galicia,Laura Cayouette,Ato Essandoh,Sammi Rotibi,Clay Donahue Fontenot,Escalante Lundy,Miriam F. Glover,Don Johnson', 'Quentin Tarantino', 'Quentin Tarantino', 'movie_image_55.jpg'),
(56, 56, 'Indiana Jones and the Raiders of the Lost Ark', 1981, 8.4, 'Action,Adventure', 'PG', '1h 55m', 'Indiana Jones - the new hero from the creators of JAWS and STAR WARS.', 18000000, 389925971, 'Harrison Ford,Karen Allen,Paul Freeman,John Rhys-Davies,Ronald Lacey,Denholm Elliott,Alfred Molina,Wolf Kahler,Anthony Higgins,Vic Tablian,Don Fellows,William Hootkins,Bill Reimbold,Fred Sorenson,Patrick Durkin,Matthew Scurfield,Malcolm Weaver,Sonny Caldinez', 'Steven Spielberg', 'Lawrence Kasdan,George Lucas,Philip Kaufman', 'movie_image_56.jpg'),
(57, 57, 'WALL·E', 2008, 8.4, 'Animation,Adventure,Family', 'G', '1h 38m', 'After 700 years of doing what he was built for - he\'ll discover what he\'s meant for.', 180000000, 521311890, 'Ben Burtt,Elissa Knight,Jeff Garlin,Fred Willard,MacInTalk,John Ratzenberger,Kathy Najimy,Sigourney Weaver,Karleen Griffin,Kim Kopf,Niki McElroy,Garrett Palmer,Jessica Skelton,Kai Steel Smith,Michael Toy', 'Andrew Stanton', 'Andrew Stanton,Pete Docter,Jim Reardon', 'movie_image_57.jpg'),
(58, 58, 'The Lives of Others', 2006, 8.4, 'Drama,Mystery,Thriller', 'R', '2h 17m', 'Before the Fall of the Berlin Wall, East Germany\'s Secret Police Listened to Your Secrets', 2000000, 77356942, 'Ulrich Mühe,Martina Gedeck,Sebastian Koch,Ulrich Tukur,Thomas Thieme,Hans-Uwe Bauer,Volkmar Kleinert,Matthias Brenner,Charly Hübner,Herbert Knaup,Bastian Trost,Marie Gruber,Volker Michalowski,Werner Daehn,Martin Brambach,Hubertus Hartmann,Thomas Arnold,Hinnerk Schönemann', 'Florian Henckel von Donnersmarck', 'Florian Henckel von Donnersmarck', 'movie_image_58.jpg'),
(59, 59, 'Sunset Blvd.', 1950, 8.4, 'Drama,Film-Noir', 'Passed', '1h 50m', 'A Hollywood Story', 1752000, 300073, 'William Holden,Gloria Swanson,Erich von Stroheim,Nancy Olson,Fred Clark,Lloyd Gough,Jack Webb,Franklyn Farnum,Larry J. Blake,Charles Dayton,Cecil B. DeMille,Hedda Hopper,Buster Keaton,Anna Q. Nilsson,H.B. Warner,Ray Evans,Jay Livingston,Fred Aldrich', 'Billy Wilder', 'Charles Brackett,Billy Wilder,D.M. Marshman Jr.', 'movie_image_59.jpg'),
(60, 60, 'Paths of Glory', 1957, 8.4, 'Drama,War', 'Approved', '1h 28m', 'Never has the screen thrust so deeply into the guts of war!', 935000, 5252, 'Kirk Douglas,Ralph Meeker,Adolphe Menjou,George Macready,Wayne Morris,Richard Anderson,Joe Turkel,Christiane Kubrick,Jerry Hausner,Peter Capell,Emile Meyer,Bert Freed,Kem Dibbs,Timothy Carey,Fred Bell,John Stein,Harold Benedict,Leon Briggs', 'Stanley Kubrick', 'Stanley Kubrick,Calder Willingham,Jim Thompson', 'movie_image_60.jpg'),
(61, 61, 'The Shining', 1980, 8.4, 'Drama,Horror', 'R', '2h 26m', 'Iconic terror from the No 1 bestselling writer.', 19000000, 47335804, 'Jack Nicholson,Shelley Duvall,Danny Lloyd,Scatman Crothers,Barry Nelson,Philip Stone,Joe Turkel,Anne Jackson,Tony Burton,Lia Beldam,Billie Gibson,Barry Dennen,David Baxt,Manning Redwood,Lisa Burns,Louise Burns,Robin Pappas,Alison Coleridge', 'Stanley Kubrick', 'Stephen King,Stanley Kubrick,Diane Johnson', 'movie_image_61.jpg'),
(62, 62, 'The Great Dictator', 1940, 8.4, 'Comedy,Drama,War', 'G', '2h 5m', 'The Comedy Masterpiece!', 2000000, 970263, 'Charles Chaplin,Paulette Goddard,Jack Oakie,Reginald Gardiner,Henry Daniell,Billy Gilbert,Grace Hayle,Carter DeHaven,Maurice Moscovitch,Emma Dunn,Bernard Gorcey,Paul Weigel,Chester Conklin,Esther Michelson,Hank Mann,Florence Wright,Eddie Gribbon,Rudolph Anders', 'Charles Chaplin', 'Charles Chaplin', 'movie_image_62.jpg'),
(63, 63, 'Avengers: Infinity War', 2018, 8.4, 'Action,Adventure,Sci-Fi', 'PG-13', '2h 29m', 'An entire universe. Once and for all.', 321000000, 2052415039, 'Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,Chris Evans,Scarlett Johansson,Don Cheadle,Benedict Cumberbatch,Tom Holland,Chadwick Boseman,Zoe Saldana,Karen Gillan,Tom Hiddleston,Paul Bettany,Elizabeth Olsen,Anthony Mackie,Sebastian Stan,Idris Elba,Danai Gurira', 'Anthony Russo,Joe Russo', 'Christopher Markus,Stephen McFeely,Stan Lee', 'movie_image_63.jpg'),
(64, 64, 'Witness for the Prosecution', 1957, 8.4, 'Crime,Drama,Mystery', 'Approved', '1h 56m', 'The most electrifying entertainment of our time!', 3000000, 7693, 'Tyrone Power,Marlene Dietrich,Charles Laughton,Elsa Lanchester,John Williams,Henry Daniell,Ian Wolfe,Torin Thatcher,Norma Varden,Una O\'Connor,Francis Compton,Philip Tonge,Ruta Lee,Patrick Aherne,Don Ames,Walter Bacon,Eddie Baker,Benjie Bancroft', 'Billy Wilder', 'Agatha Christie,Billy Wilder,Harry Kurnitz', 'movie_image_64.jpg'),
(65, 65, 'Aliens', 1986, 8.4, 'Action,Adventure,Sci-Fi', 'R', '2h 17m', 'This time there\'s more.', 18500000, 131060248, 'Sigourney Weaver,Michael Biehn,Carrie Henn,Paul Reiser,Lance Henriksen,Bill Paxton,William Hope,Jenette Goldstein,Al Matthews,Mark Rolston,Ricco Ross,Colette Hiller,Daniel Kash,Cynthia Dale Scott,Tip Tipping,Trevor Steedman,Paul Maxwell,Valerie Colgan', 'James Cameron', 'James Cameron,David Giler,Walter Hill', 'movie_image_65.jpg'),
(66, 66, 'Spider-Man: Into the Spider-Verse', 2018, 8.4, 'Animation,Action,Adventure', 'PG', '1h 57m', 'Enter a universe where more than one wears the mask.', NULL, NULL, 'Shameik Moore,Jake Johnson,Hailee Steinfeld,Mahershala Ali,Brian Tyree Henry,Lily Tomlin,Luna Lauren Velez,Zoë Kravitz,John Mulaney,Kimiko Glenn,Nicolas Cage,Kathryn Hahn,Liev Schreiber,Chris Pine,Natalie Morales,Edwin R. Habacon,Oscar Isaac,Greta Lee', 'Bob Persichetti,Peter Ramsey,Rodney Rothman', 'Phil Lord,Rodney Rothman', 'movie_image_66.jpg'),
(67, 67, 'American Beauty', 1999, 8.4, 'Drama', 'R', '2h 2m', '... look closer', 15000000, 356296601, 'Kevin Spacey,Annette Bening,Thora Birch,Wes Bentley,Mena Suvari,Peter Gallagher,Allison Janney,Chris Cooper,Scott Bakula,Sam Robards,Barry Del Sherman,Ara Celi,John Cho,Fort Atkinson,Sue Casey,Kent Faulcon,Brenda Wehle,Lisa Cloud', 'Sam Mendes', 'Alan Ball', 'movie_image_67.jpg'),
(68, 68, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 1964, 8.4, 'Comedy,War', 'PG', '1h 35m', 'The comedy classic from celebrated director STANLEY KUBRICK', 1800000, 9523464, 'Peter Sellers,George C. Scott,Sterling Hayden,Keenan Wynn,Slim Pickens,Peter Bull,James Earl Jones,Tracy Reed,Jack Creley,Frank Berry,Robert O\'Neil,Glenn Beck,Roy Stephens,Shane Rimmer,Hal Galili,Paul Tamarin,Laurence Herder,Gordon Tanner', 'Stanley Kubrick', 'Stanley Kubrick,Terry Southern,Peter George', 'movie_image_68.jpg'),
(69, 69, 'The Dark Knight Rises', 2012, 8.4, 'Action,Drama', 'PG-13', '2h 44m', 'The Legend Ends', 250000000, 1081169825, 'Christian Bale,Tom Hardy,Anne Hathaway,Gary Oldman,Joseph Gordon-Levitt,Marion Cotillard,Morgan Freeman,Michael Caine,Matthew Modine,Alon Aboutboul,Ben Mendelsohn,Burn Gorman,Daniel Sunjata,Aidan Gillen,Sam Kennard,Aliash Tepina,Nestor Carbonell,Brett Cullen', 'Christopher Nolan', 'Jonathan Nolan,Christopher Nolan,David S. Goyer', 'movie_image_69.jpg'),
(70, 70, 'Oldboy', 2003, 8.4, 'Action,Drama,Mystery', 'R', '2h', '15 years of imprisonment, five days of vengeance', 3000000, 15421226, 'Choi Min-sik,Yoo Ji-tae,Kang Hye-jeong,Kim Byeong-Ok,Dae-han Ji,Dal-su Oh,Seung-shin Lee,Jin-Seo Yoon,Tae-kyung Oh,Yoo Yeon-Seok,Il-han Oo,Young-hee Lee,Young-ae Kim,Mi Mi Lee,Jae-Duk Han,Jung Ae Kwak,San Kim,Chae-soo Jang', 'Park Chan-wook', 'Garon Tsuchiya,Nobuaki Minegishi,Park Chan-wook', 'movie_image_70.jpg'),
(71, 71, 'Inglourious Basterds', 2009, 8.3, 'Adventure,Drama,War', 'R', '2h 33m', 'Once upon a time in Nazi occupied France...', 70000000, 321457747, 'Brad Pitt,Diane Kruger,Eli Roth,Mélanie Laurent,Christoph Waltz,Michael Fassbender,Daniel Brühl,Til Schweiger,Gedeon Burkhard,Jacky Ido,B.J. Novak,Omar Doom,August Diehl,Denis Ménochet,Sylvester Groth,Martin Wuttke,Mike Myers,Julie Dreyfus', 'Quentin Tarantino', 'Quentin Tarantino', 'movie_image_71.jpg'),
(72, 72, 'Amadeus', 1984, 8.4, 'Biography,Drama,Music', 'PG', '2h 40m', 'The man... The music... The madness... The murder... The motion picture...', 18000000, 52066791, 'F. Murray Abraham,Tom Hulce,Elizabeth Berridge,Roy Dotrice,Simon Callow,Christine Ebersole,Jeffrey Jones,Charles Kay,Kenneth McMillan,Kenny Baker,Lisbeth Bartlett,Barbara Bryne,Martin Cavina,Roderick Cook,Milan Demjanenko,Peter DiGesu,Richard Frank,Patrick Hines', 'Milos Forman', 'Peter Shaffer,Zdenek Mahler', 'movie_image_72.jpg'),
(73, 73, 'Coco', 2017, 8.4, 'Animation,Adventure,Comedy', 'PG', '1h 45m', 'The celebration of a lifetime', 175000000, 814337054, 'Anthony Gonzalez,Gael García Bernal,Benjamin Bratt,Alanna Ubach,Renee Victor,Jaime Camil,Alfonso Arau,Herbert Siguenza,Gabriel Iglesias,Lombardo Boyar,Ana Ofelia Murguía,Natalia Cordova-Buckley,Selene Luna,Edward James Olmos,Sofía Espinosa,Carla Medina,Dyana Ortelli,Luis Valdez', 'Lee Unkrich,Adrian Molina(co-directed by)', 'Lee Unkrich,Jason Katz,Matthew Aldrich', 'movie_image_73.jpg'),
(74, 74, 'Toy Story', 1995, 8.3, 'Animation,Adventure,Comedy', 'G', '1h 21m', 'Oooh...3-D (USA 2009 re-release)', 30000000, 394436586, 'Tom Hanks,Tim Allen,Don Rickles,Jim Varney,Wallace Shawn,John Ratzenberger,Annie Potts,John Morris,Erik von Detten,Laurie Metcalf,R. Lee Ermey,Sarah Rayne,Penn Jillette,Jack Angel,Spencer Aste,Greg Berg,Lisa Bradley,Kendall Cunningham', 'John Lasseter', 'John Lasseter,Pete Docter,Andrew Stanton', 'movie_image_74.jpg'),
(75, 75, 'Joker', 2019, 8.4, 'Crime,Drama,Thriller', 'R', '2h 2m', 'Put on a happy face.', 55000000, 1074458282, 'Joaquin Phoenix,Robert De Niro,Zazie Beetz,Frances Conroy,Brett Cullen,Shea Whigham,Bill Camp,Glenn Fleshler,Leigh Gill,Josh Pais,Rocco Luna,Marc Maron,Sondra James,Murphy Guyer,Douglas Hodge,Dante Pereira-Olson,Carrie Louise Putrello,Sharon Washington', 'Todd Phillips', 'Todd Phillips,Scott Silver,Bob Kane', 'movie_image_75.jpg'),
(76, 76, 'Braveheart', 1995, 8.4, 'Biography,Drama,History', 'R', '2h 58m', 'The story of a man with a free soul...and with the courage to follow it.', 72000000, 213216216, 'Mel Gibson,Sophie Marceau,Patrick McGoohan,Angus Macfadyen,James Robinson,Sean Lawlor,Sandy Nelson,James Cosmo,Sean McGinley,Alan Tall,Andrew Weir,Gerda Stevenson,Ralph Riach,Mhairi Calvey,Brian Cox,Peter Hanly,Stephen Billington,Barry McGovern', 'Mel Gibson', 'Randall Wallace', 'movie_image_76.jpg'),
(77, 77, 'The Boat', 1981, 8.4, 'Drama,War', 'Not Available', 'Not Availa', 'This is the story of 42 raw recruits caught up in a war they didn\'t understand, and the Captain who must lead them in their struggle to survive.', 32000000, 11487676, 'Jürgen Prochnow,Herbert Grönemeyer,Klaus Wennemann,Hubertus Bengsch,Martin Semmelrogge,Bernd Tauber,Erwin Leder,Martin May,Heinz Hoenig,Uwe Ochsenknecht,Claude-Oliver Rudolph,Jan Fedder,Ralf Richter,Joachim Bernhard,Oliver Stritzel,Konrad Becker,Lutz Schnell,Martin Hemme', 'Wolfgang Petersen', 'Wolfgang Petersen,Lothar G. Buchheim', 'movie_image_77.jpg'),
(78, 78, 'Avengers: Endgame', 2019, 8.4, 'Action,Adventure,Drama', 'PG-13', '3h 1m', 'Avenge the fallen.', 356000000, 2799439100, 'Robert Downey Jr.,Chris Evans,Mark Ruffalo,Chris Hemsworth,Scarlett Johansson,Jeremy Renner,Don Cheadle,Paul Rudd,Benedict Cumberbatch,Chadwick Boseman,Brie Larson,Tom Holland,Karen Gillan,Zoe Saldana,Evangeline Lilly,Tessa Thompson,Rene Russo,Elizabeth Olsen', 'Anthony Russo,Joe Russo', 'Christopher Markus,Stephen McFeely,Stan Lee', 'movie_image_78.jpg'),
(79, 79, 'Princess Mononoke', 1997, 8.4, 'Animation,Action,Adventure', 'PG-13', '2h 14m', 'Live on.', 2400000000, 170005875, 'Yôji Matsuda,Yuriko Ishida,Yûko Tanaka,Billy Crudup,Billy Bob Thornton,Minnie Driver,John DiMaggio,Claire Danes,John DeMita,Jada Pinkett Smith,Gillian Anderson,Keith David,Corey Burton,Tara Strong,Julia Fletcher,Debi Derryberry,Alex Fernandez,Jack Fletcher', 'Hayao Miyazaki', 'Hayao Miyazaki,Neil Gaiman', 'movie_image_79.jpg'),
(80, 80, 'Once Upon a Time in America', 1984, 8.3, 'Crime,Drama', 'R', '3h 49m', 'Crime, passion and lust for power - Sergio Leone\'s explosive saga of gangland America.', 30000000, 5473337, 'Robert De Niro,James Woods,Elizabeth McGovern,Treat Williams,Tuesday Weld,Burt Young,Joe Pesci,Danny Aiello,William Forsythe,James Hayden,Darlanne Fluegel,Larry Rapp,Dutch Miller,Robert Harper,Richard Bright,Gerard Murphy,Amy Ryder,Olga Karlatos', 'Sergio Leone', 'Harry Grey,Leonardo Benvenuti,Piero De Bernardi', 'movie_image_80.jpg'),
(81, 81, 'Good Will Hunting', 1997, 8.3, 'Drama,Romance', 'R', '2h 6m', 'Some people can never believe in themselves, until someone believes in them.', NULL, NULL, 'Robin Williams,Matt Damon,Ben Affleck,Stellan Skarsgård,John Mighton,Rachel Majorowski,Colleen McCauley,Casey Affleck,Cole Hauser,Matt Mercier,Ralph St. George,Rob Lynds,Dan Washington,Alison Folland,Derrick Bridgeman,Vik Sahay,Shannon Egleson,Rob Lyons', 'Gus Van Sant', 'Matt Damon,Ben Affleck', 'movie_image_81.jpg'),
(82, 82, 'Your Name.', 2016, 8.4, 'Animation,Drama,Fantasy', 'TV-PG', '1h 46m', 'Experience Japan\'s #1 film of 2016, from visionary director Makoto Shinkai', NULL, NULL, 'Ryûnosuke Kamiki,Mone Kamishiraishi,Ryô Narita,Aoi Yûki,Nobunaga Shimazaki,Kaito Ishikawa,Kanon Tani,Masaki Terasoma,Sayaka Ôhara,Kazuhiko Inoue,Chafûrin,Kana Hanazawa,Yuka Terasaki,Takashi Onozuka,Yôhei Namekawa,Miyu Tsuji,Shin\'ya Hamazoe,Kanami Satô', 'Makoto Shinkai', 'Makoto Shinkai,Clark Cheng', 'movie_image_82.jpg'),
(83, 83, '3 Idiots', 2009, 8.4, 'Comedy,Drama', 'PG-13', '2h 50m', 'Don\'t be Stupid. Be an I.D.I.O.T.', 550000000, 60262836, 'Aamir Khan,Madhavan,Mona Singh,Sharman Joshi,Kareena Kapoor,Boman Irani,Omi Vaidya,Olivier Lafont,Rahul Kumar,Parikshit Sahni,Farida Dadi,Amardeep Jha,Mukund Bhatt,Chaitali Bose,Jaaved Jaaferi,Jayant Kripalani,Arun Bali,Shoaib Ahmed', 'Rajkumar Hirani', 'Rajkumar Hirani,Abhijat Joshi,Vidhu Vinod Chopra', 'movie_image_83.jpg'),
(84, 84, 'Singin\' in the Rain', 1952, 8.3, 'Comedy,Musical,Romance', 'G', '1h 43m', 'Singin\' Swingin\' Glorious Feelin\' Technicolor Musical', 2540800, 2000288, 'Gene Kelly,Donald O\'Connor,Debbie Reynolds,Jean Hagen,Millard Mitchell,Cyd Charisse,Douglas Fowley,Rita Moreno,Dawn Addams,John Albright,Betty Allen,Sue Allen,John Angelo,Marie Ardell,Bette Arlen,David Bair,Lynn Bari,Jimmy Bates', 'Stanley Donen,Gene Kelly', 'Betty Comden,Adolph Green', 'movie_image_84.jpg'),
(85, 85, 'Requiem for a Dream', 2000, 8.3, 'Drama', 'Unrated', '1h 42m', 'From the director of [Pi]', 4500000, 7390108, 'Ellen Burstyn,Jared Leto,Jennifer Connelly,Marlon Wayans,Christopher McDonald,Louise Lasser,Marcia Jean Kurtz,Janet Sarno,Suzanne Shepherd,Joanne Gordon,Charlotte Aronofsky,Mark Margolis,Michael Kaycheck,Jack O\'Connell,Chas Mastin,Ajay Naidu,Sean Gullette,Samia Shoaib', 'Darren Aronofsky', 'Hubert Selby Jr.,Darren Aronofsky', 'movie_image_85.jpg'),
(86, 86, 'Toy Story 3', 2010, 8.3, 'Animation,Adventure,Comedy', 'G', '1h 43m', 'The Breakout Comedy Of The Summer', 200000000, 1067316101, 'Tom Hanks,Tim Allen,Joan Cusack,Ned Beatty,Don Rickles,Michael Keaton,Wallace Shawn,John Ratzenberger,Estelle Harris,John Morris,Jodi Benson,Emily Ricks Hahn,Laurie Metcalf,Blake Clark,Teddy Newton,Bea Miller,Javier Fernández-Peña', 'Lee Unkrich', 'John Lasseter,Andrew Stanton,Lee Unkrich', 'movie_image_86.jpg'),
(87, 87, 'High and Low', 1963, 8.4, 'Crime,Drama,Mystery', 'Not Rated', '2h 23m', '142 Screenful Minutes of Thrills and Suspense!', NULL, NULL, 'Toshirô Mifune,Yutaka Sada,Tatsuya Nakadai,Kyôko Kagawa,Tatsuya Mihashi,Isao Kimura,Kenjirô Ishiyama,Takeshi Katô,Takashi Shimura,Jun Tazaki,Nobuo Nakamura,Yûnosuke Itô,Tsutomu Yamazaki,Minoru Chiaki,Eijirô Tôno,Masao Shimizu,Masahiko Shimazu,Toshio Egi', 'Akira Kurosawa', 'Hideo Oguni,Ryûzô Kikushima,Eijirô Hisaita', 'movie_image_87.jpg'),
(88, 88, 'Capernaum', 2018, 8.4, 'Drama', 'R', '2h 6m', 'Why are you suing your parents? For giving me life.', NULL, NULL, 'Zain Al Rafeea,Yordanos Shiferaw,Boluwatife Treasure Bankole,Kawsar Al Haddad,Fadi Yousef,Cedra Izzam,Alaa Chouchnieh,Elias Khoury,Mohammad Al Abdallah,Mohamad Abdellatif,Abdo Abdo,Hampig Abraham,Jamil Ahmad,Mohamad Akkar,Elias Akobegia,Riman Al Rafeea,Legamett Alamou,Majd Nabil Alhalabi', 'Nadine Labaki', 'Nadine Labaki,Jihad Hojeily,Michelle Keserwany', 'movie_image_88.jpg'),
(89, 89, 'Star Wars: Episode VI - Return of the Jedi', 1983, 8.3, 'Action,Adventure,Fantasy', 'PG', '2h 11m', 'Coming May 25, 1983 to your galaxy. [Second Advance poster]', 32500000, 475106177, 'Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,Anthony Daniels,Peter Mayhew,Sebastian Shaw,Ian McDiarmid,Frank Oz,James Earl Jones,David Prowse,Alec Guinness,Kenny Baker,Michael Pennington,Kenneth Colley,Michael Carter,Denis Lawson,Tim Rose', 'Richard Marquand', 'Lawrence Kasdan,George Lucas', 'movie_image_89.jpg'),
(90, 90, 'Eternal Sunshine of the Spotless Mind', 2004, 8.3, 'Drama,Romance,Sci-Fi', 'R', '1h 48m', 'I already forget how I used to feel about you.', 20000000, 74036715, 'Jim Carrey,Kate Winslet,Tom Wilkinson,Gerry Robert Byrne,Elijah Wood,Thomas Jay Ryan,Mark Ruffalo,Jane Adams,David Cross,Kirsten Dunst,Ryan Whitney,Debbon Ayer,Amir Ali Said,Brian Price,Paulie Litt,Josh Flitter,Lola Daehler,Deirdre O\'Connell', 'Michel Gondry', 'Charlie Kaufman,Michel Gondry,Pierre Bismuth', 'movie_image_90.jpg'),
(91, 91, '2001: A Space Odyssey', 1968, 8.3, 'Adventure,Sci-Fi', 'G', '2h 29m', 'Let the Awe and Mystery of a Journey Unlike Any Other Begin', 12000000, 65889846, 'Keir Dullea,Gary Lockwood,William Sylvester,Daniel Richter,Leonard Rossiter,Margaret Tyzack,Robert Beatty,Sean Sullivan,Douglas Rain,Frank Miller,Bill Weston,Ed Bishop,Glenn Beck,Alan Gifford,Ann Gillis,Edwina Carroll,Penny Brahms,Heather Downham', 'Stanley Kubrick', 'Stanley Kubrick,Arthur C. Clarke', 'movie_image_91.jpg'),
(92, 92, 'Reservoir Dogs', 1992, 8.3, 'Crime,Thriller', 'R', '1h 39m', 'Seven Total Strangers Team Up For The Perfect Crime. They Don\'t Know Each Other\'s Name. But They\'ve Got Each Other\'s Color', 1200000, 2913644, 'Harvey Keitel,Tim Roth,Michael Madsen,Chris Penn,Steve Buscemi,Lawrence Tierney,Randy Brooks,Kirk Baltz,Edward Bunker,Quentin Tarantino,Rich Turner,David Steen,Tony Cosmo,Stevo Polyi,Michael Sottile,Robert Ruth,Lawrence Bender,Linda Kaye', 'Quentin Tarantino', 'Quentin Tarantino,Roger Avary', 'movie_image_92.jpg'),
(93, 93, 'Come and See', 1985, 8.4, 'Drama,Thriller,War', 'Not Rated', '2h 22m', 'The cruelest side of war.', NULL, NULL, 'Aleksey Kravchenko,Olga Mironova,Liubomiras Laucevicius,Vladas Bagdonas,Jüri Lumiste,Viktors Lorencs,Kazimir Rabetsky,Evgeniy Tilicheev,G. Velts,V. Vasilyev,Aleksandr Berda,Vasiliy Domrachyov,Nina Evdokimova,Igor Gnevashev,Adolf Hitler,Valery Kravchenko,Evgeniy Kryzhanovskiy,N. Lisichenok', 'Elem Klimov', 'Ales Adamovich,Elem Klimov', 'movie_image_93.jpg'),
(94, 94, 'The Hunt', 2012, 8.3, 'Drama', 'R', '1h 55m', 'The lie is spreading.', NULL, NULL, 'Mads Mikkelsen,Thomas Bo Larsen,Annika Wedderkopp,Lasse Fogelstrøm,Susse Wold,Anne Louise Hassing,Lars Ranthe,Alexandra Rapaport,Sebastian Bull,Steen Ordell Guldbrand Jensen,Daniel Engstrup,Troels Thorsen,Søren Rønholt,Hana Shuan,Jytte Kvinesdal,Josefine Gråbøl,Bjarne Henriksen,Nicolai Dahl Hamilton', 'Thomas Vinterberg', 'Thomas Vinterberg,Tobias Lindholm', 'movie_image_94.jpg'),
(95, 95, 'Citizen Kane', 1941, 8.3, 'Drama,Mystery', 'PG', '1h 59m', 'Radio\'s Most Dynamic Artist . . The Man At Whose Voice A Nation Trembled . . . Now the screen\'s most exciting NEW star ! ORSON WELLES in the picture Hollywood said he\'d never make', 839727, 1645133, 'Orson Welles,Joseph Cotten,Dorothy Comingore,Agnes Moorehead,Ruth Warrick,Ray Collins,Erskine Sanford,Everett Sloane,William Alland,Paul Stewart,George Coulouris,Fortunio Bonanova,Gus Schilling,Philip Van Zandt,Georgia Backus,Harry Shannon,Sonny Bupp,Buddy Swan', 'Orson Welles', 'Herman J. Mankiewicz,Orson Welles,John Houseman', 'movie_image_95.jpg'),
(96, 96, 'M', 1931, 8.3, 'Crime,Mystery,Thriller', 'Passed', '1h 39m', 'IT STAGGERS THE SENSES!...SHOCKS the Imagination - It will leave you Gasping - It is the Sensation of 3 Continents!', NULL, 35566, 'Peter Lorre,Ellen Widmann,Inge Landgut,Otto Wernicke,Theodor Loos,Gustaf Gründgens,Friedrich Gnaß,Fritz Odemar,Paul Kemp,Theo Lingen,Rudolf Blümner,Georg John,Franz Stein,Ernst Stahl-Nachbaur,Gerhard Bienert,Karl Platen,Rosa Valetti,Hertha von Walther', 'Fritz Lang', 'Thea von Harbou,Fritz Lang,Egon Jacobsohn', 'movie_image_96.jpg'),
(97, 97, 'Lawrence of Arabia', 1962, 8.3, 'Adventure,Biography,Drama', 'Approved', '3h 38m', 'A Mighty Motion Picture Of Action And Adventure!', 15000000, 45720631, 'Peter O\'Toole,Alec Guinness,Anthony Quinn,Jack Hawkins,Omar Sharif,José Ferrer,Anthony Quayle,Claude Rains,Arthur Kennedy,Donald Wolfit,I.S. Johar,Gamil Ratib,Michel Ray,John Dimech,Zia Mohyeddin,Howard Marion-Crawford,Jack Gwillim,Hugh Miller', 'David Lean', 'Robert Bolt,Michael Wilson', 'movie_image_97.jpg'),
(98, 98, 'North by Northwest', 1959, 8.3, 'Action,Adventure,Mystery', 'Approved', '2h 16m', 'Alfred Hitchcock takes you.... North by Northwest!', 3101000, 142319, 'Cary Grant,Eva Marie Saint,James Mason,Jessie Royce Landis,Leo G. Carroll,Josephine Hutchinson,Philip Ober,Martin Landau,Adam Williams,Edward Platt,Robert Ellenstein,Les Tremayne,Philip Coolidge,Patrick McVey,Edward Binns,Ken Lynch,Stanley Adams,John Alban', 'Alfred Hitchcock', 'Ernest Lehman', 'movie_image_98.jpg'),
(99, 99, 'Vertigo', 1958, 8.3, 'Mystery,Romance,Thriller', 'PG', '2h 8m', 'A Hitchcock thriller. You should see it from the beginning!', 2479000, 7798146, 'James Stewart,Kim Novak,Barbara Bel Geddes,Tom Helmore,Henry Jones,Raymond Bailey,Ellen Corby,Konstantin Shayne,Lee Patrick,David Ahdar,Isabel Analla,Jack Ano,Margaret Bacon,John Benson,Danny Borzage,Margaret Brayton,Paul Bryar,Boyd Cabeen', 'Alfred Hitchcock', 'Alec Coppel,Samuel A. Taylor,Pierre Boileau', 'movie_image_99.jpg'),
(100, 100, 'Ikiru', 1952, 8.3, 'Drama', 'Not Rated', '2h 23m', 'One of the Great Films of Our Time!', NULL, 96302, 'Takashi Shimura,Nobuo Kaneko,Shin\'ichi Himori,Haruo Tanaka,Minoru Chiaki,Miki Odagiri,Bokuzen Hidari,Minosuke Yamada,Kamatari Fujiwara,Makoto Kobori,Nobuo Nakamura,Atsushi Watanabe,Isao Kimura,Masao Shimizu,Yûnosuke Itô,Kumeko Urabe,Eiko Miyoshi,Noriko Honma', 'Akira Kurosawa', 'Akira Kurosawa,Shinobu Hashimoto,Hideo Oguni', 'movie_image_100.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `playlists`
--

CREATE TABLE `playlists` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `movie_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `playlists`
--

INSERT INTO `playlists` (`id`, `user_id`, `movie_id`) VALUES
(15, 2, 4);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `email`, `password`) VALUES
(1, 'mahmoud', 'mah.ibra.ca@gmail.com', '$2y$10$LNoKrVdFow07Z0UTjEiwKekAB6nd8hrQgTxiYs1xLxhHuLwHP6gly'),
(2, 'dodo', 'dodo@dodo.com', '$2y$10$oq.606GHCWrYhxOBlw3GPeWko0zKMzHKcaMgZvib0rdGR4eqq.iLi');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `movies`
--
ALTER TABLE `movies`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `playlists`
--
ALTER TABLE `playlists`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `movies`
--
ALTER TABLE `movies`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;

--
-- AUTO_INCREMENT for table `playlists`
--
ALTER TABLE `playlists`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `playlists`
--
ALTER TABLE `playlists`
  ADD CONSTRAINT `playlists_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
